/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as LiquidStakingContractJson } from "./LiquidStaking.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts-registry";

// Custom types for the contract
export namespace LiquidStakingTypes {
  export type Fields = {
    tokenId: HexString;
    symbol: HexString;
    name: HexString;
    inflationPool: bigint;
    inflationRate: bigint;
    gainPerMillisecond: bigint;
    updatedAt: bigint;
    currentXTokenPrice: bigint;
    rewardPool: bigint;
    totalSupply: bigint;
    owner_: Address;
    paused_: boolean;
  };

  export type State = ContractState<Fields>;

  export type MintEvent = ContractEvent<{
    sender: Address;
    amount: bigint;
    newSupply: bigint;
  }>;
  export type BurnEvent = ContractEvent<{
    sender: Address;
    amount: bigint;
    newSupply: bigint;
  }>;
  export type PriceChangedEvent = ContractEvent<{ newPrice: bigint }>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    pause: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    unpause: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    whenNotPaused: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    onlyOwner: {
      params: CallContractParams<{ caller: Address }>;
      result: CallContractResult<null>;
    };
    changeOwner: {
      params: CallContractParams<{ newOwner: Address }>;
      result: CallContractResult<null>;
    };
    getCurrentRewardPerXToken: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getCurrentInflationPerXToken: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getCurrentPrice: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    updatePrice: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    mint: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    burn: {
      params: CallContractParams<{ xTokenAmount: bigint }>;
      result: CallContractResult<null>;
    };
    topUpRewards: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    topUpInflationPool: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    setGainPerMillisecond: {
      params: CallContractParams<{ newGainPerMillisecond: bigint }>;
      result: CallContractResult<null>;
    };
    setInflationRate: {
      params: CallContractParams<{ newInflationRate: bigint }>;
      result: CallContractResult<null>;
    };
    getTokenId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    upgrade: {
      params: CallContractParams<{ newBytecode: HexString }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getSymbol: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDecimals: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    pause: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    unpause: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    whenNotPaused: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    onlyOwner: {
      params: SignExecuteContractMethodParams<{ caller: Address }>;
      result: SignExecuteScriptTxResult;
    };
    changeOwner: {
      params: SignExecuteContractMethodParams<{ newOwner: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getCurrentRewardPerXToken: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getCurrentInflationPerXToken: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getCurrentPrice: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    updatePrice: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    mint: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    burn: {
      params: SignExecuteContractMethodParams<{ xTokenAmount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    topUpRewards: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    topUpInflationPool: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    setGainPerMillisecond: {
      params: SignExecuteContractMethodParams<{
        newGainPerMillisecond: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    setInflationRate: {
      params: SignExecuteContractMethodParams<{ newInflationRate: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getTokenId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    upgrade: {
      params: SignExecuteContractMethodParams<{ newBytecode: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  LiquidStakingInstance,
  LiquidStakingTypes.Fields
> {
  encodeFields(fields: LiquidStakingTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Mint: 0, Burn: 1, PriceChanged: 2 };
  consts = {
    PermissionsErrorCodes: { Forbidden: BigInt("0") },
    PauseableErrorCodes: { Paused: BigInt("0") },
  };

  at(address: string): LiquidStakingInstance {
    return new LiquidStakingInstance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParamsWithoutMaps<LiquidStakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSymbol", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<LiquidStakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDecimals: async (
      params: Omit<
        TestContractParamsWithoutMaps<LiquidStakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDecimals", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<LiquidStakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
    pause: async (
      params: Omit<
        TestContractParamsWithoutMaps<LiquidStakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "pause", params, getContractByCodeHash);
    },
    unpause: async (
      params: Omit<
        TestContractParamsWithoutMaps<LiquidStakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "unpause", params, getContractByCodeHash);
    },
    whenNotPaused: async (
      params: Omit<
        TestContractParamsWithoutMaps<LiquidStakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "whenNotPaused", params, getContractByCodeHash);
    },
    onlyOwner: async (
      params: TestContractParamsWithoutMaps<
        LiquidStakingTypes.Fields,
        { caller: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "onlyOwner", params, getContractByCodeHash);
    },
    changeOwner: async (
      params: TestContractParamsWithoutMaps<
        LiquidStakingTypes.Fields,
        { newOwner: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "changeOwner", params, getContractByCodeHash);
    },
    getCurrentRewardPerXToken: async (
      params: Omit<
        TestContractParamsWithoutMaps<LiquidStakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getCurrentRewardPerXToken",
        params,
        getContractByCodeHash
      );
    },
    getCurrentInflationPerXToken: async (
      params: Omit<
        TestContractParamsWithoutMaps<LiquidStakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "getCurrentInflationPerXToken",
        params,
        getContractByCodeHash
      );
    },
    getCurrentPrice: async (
      params: Omit<
        TestContractParamsWithoutMaps<LiquidStakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getCurrentPrice", params, getContractByCodeHash);
    },
    updatePrice: async (
      params: Omit<
        TestContractParamsWithoutMaps<LiquidStakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "updatePrice", params, getContractByCodeHash);
    },
    mint: async (
      params: TestContractParamsWithoutMaps<
        LiquidStakingTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "mint", params, getContractByCodeHash);
    },
    burn: async (
      params: TestContractParamsWithoutMaps<
        LiquidStakingTypes.Fields,
        { xTokenAmount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "burn", params, getContractByCodeHash);
    },
    topUpRewards: async (
      params: TestContractParamsWithoutMaps<
        LiquidStakingTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "topUpRewards", params, getContractByCodeHash);
    },
    topUpInflationPool: async (
      params: TestContractParamsWithoutMaps<
        LiquidStakingTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "topUpInflationPool",
        params,
        getContractByCodeHash
      );
    },
    setGainPerMillisecond: async (
      params: TestContractParamsWithoutMaps<
        LiquidStakingTypes.Fields,
        { newGainPerMillisecond: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "setGainPerMillisecond",
        params,
        getContractByCodeHash
      );
    },
    setInflationRate: async (
      params: TestContractParamsWithoutMaps<
        LiquidStakingTypes.Fields,
        { newInflationRate: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "setInflationRate",
        params,
        getContractByCodeHash
      );
    },
    getTokenId: async (
      params: Omit<
        TestContractParamsWithoutMaps<LiquidStakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getTokenId", params, getContractByCodeHash);
    },
    upgrade: async (
      params: TestContractParamsWithoutMaps<
        LiquidStakingTypes.Fields,
        { newBytecode: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "upgrade", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: LiquidStakingTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const LiquidStaking = new Factory(
  Contract.fromJson(
    LiquidStakingContractJson,
    "",
    "bc3c9e8d9c41eb8cee49a169c0201ce7774a90e7b68d7fba94badb71c55c2742",
    []
  )
);
registerContract(LiquidStaking);

// Use this class to interact with the blockchain
export class LiquidStakingInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<LiquidStakingTypes.State> {
    return fetchContractState(LiquidStaking, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeMintEvent(
    options: EventSubscribeOptions<LiquidStakingTypes.MintEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LiquidStaking.contract,
      this,
      options,
      "Mint",
      fromCount
    );
  }

  subscribeBurnEvent(
    options: EventSubscribeOptions<LiquidStakingTypes.BurnEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LiquidStaking.contract,
      this,
      options,
      "Burn",
      fromCount
    );
  }

  subscribePriceChangedEvent(
    options: EventSubscribeOptions<LiquidStakingTypes.PriceChangedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      LiquidStaking.contract,
      this,
      options,
      "PriceChanged",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | LiquidStakingTypes.MintEvent
      | LiquidStakingTypes.BurnEvent
      | LiquidStakingTypes.PriceChangedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(
      LiquidStaking.contract,
      this,
      options,
      fromCount
    );
  }

  view = {
    getSymbol: async (
      params?: LiquidStakingTypes.CallMethodParams<"getSymbol">
    ): Promise<LiquidStakingTypes.CallMethodResult<"getSymbol">> => {
      return callMethod(
        LiquidStaking,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: LiquidStakingTypes.CallMethodParams<"getName">
    ): Promise<LiquidStakingTypes.CallMethodResult<"getName">> => {
      return callMethod(
        LiquidStaking,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: LiquidStakingTypes.CallMethodParams<"getDecimals">
    ): Promise<LiquidStakingTypes.CallMethodResult<"getDecimals">> => {
      return callMethod(
        LiquidStaking,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: LiquidStakingTypes.CallMethodParams<"getTotalSupply">
    ): Promise<LiquidStakingTypes.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        LiquidStaking,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    pause: async (
      params?: LiquidStakingTypes.CallMethodParams<"pause">
    ): Promise<LiquidStakingTypes.CallMethodResult<"pause">> => {
      return callMethod(
        LiquidStaking,
        this,
        "pause",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    unpause: async (
      params?: LiquidStakingTypes.CallMethodParams<"unpause">
    ): Promise<LiquidStakingTypes.CallMethodResult<"unpause">> => {
      return callMethod(
        LiquidStaking,
        this,
        "unpause",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    whenNotPaused: async (
      params?: LiquidStakingTypes.CallMethodParams<"whenNotPaused">
    ): Promise<LiquidStakingTypes.CallMethodResult<"whenNotPaused">> => {
      return callMethod(
        LiquidStaking,
        this,
        "whenNotPaused",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    onlyOwner: async (
      params: LiquidStakingTypes.CallMethodParams<"onlyOwner">
    ): Promise<LiquidStakingTypes.CallMethodResult<"onlyOwner">> => {
      return callMethod(
        LiquidStaking,
        this,
        "onlyOwner",
        params,
        getContractByCodeHash
      );
    },
    changeOwner: async (
      params: LiquidStakingTypes.CallMethodParams<"changeOwner">
    ): Promise<LiquidStakingTypes.CallMethodResult<"changeOwner">> => {
      return callMethod(
        LiquidStaking,
        this,
        "changeOwner",
        params,
        getContractByCodeHash
      );
    },
    getCurrentRewardPerXToken: async (
      params?: LiquidStakingTypes.CallMethodParams<"getCurrentRewardPerXToken">
    ): Promise<
      LiquidStakingTypes.CallMethodResult<"getCurrentRewardPerXToken">
    > => {
      return callMethod(
        LiquidStaking,
        this,
        "getCurrentRewardPerXToken",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getCurrentInflationPerXToken: async (
      params?: LiquidStakingTypes.CallMethodParams<"getCurrentInflationPerXToken">
    ): Promise<
      LiquidStakingTypes.CallMethodResult<"getCurrentInflationPerXToken">
    > => {
      return callMethod(
        LiquidStaking,
        this,
        "getCurrentInflationPerXToken",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getCurrentPrice: async (
      params?: LiquidStakingTypes.CallMethodParams<"getCurrentPrice">
    ): Promise<LiquidStakingTypes.CallMethodResult<"getCurrentPrice">> => {
      return callMethod(
        LiquidStaking,
        this,
        "getCurrentPrice",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    updatePrice: async (
      params?: LiquidStakingTypes.CallMethodParams<"updatePrice">
    ): Promise<LiquidStakingTypes.CallMethodResult<"updatePrice">> => {
      return callMethod(
        LiquidStaking,
        this,
        "updatePrice",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    mint: async (
      params: LiquidStakingTypes.CallMethodParams<"mint">
    ): Promise<LiquidStakingTypes.CallMethodResult<"mint">> => {
      return callMethod(
        LiquidStaking,
        this,
        "mint",
        params,
        getContractByCodeHash
      );
    },
    burn: async (
      params: LiquidStakingTypes.CallMethodParams<"burn">
    ): Promise<LiquidStakingTypes.CallMethodResult<"burn">> => {
      return callMethod(
        LiquidStaking,
        this,
        "burn",
        params,
        getContractByCodeHash
      );
    },
    topUpRewards: async (
      params: LiquidStakingTypes.CallMethodParams<"topUpRewards">
    ): Promise<LiquidStakingTypes.CallMethodResult<"topUpRewards">> => {
      return callMethod(
        LiquidStaking,
        this,
        "topUpRewards",
        params,
        getContractByCodeHash
      );
    },
    topUpInflationPool: async (
      params: LiquidStakingTypes.CallMethodParams<"topUpInflationPool">
    ): Promise<LiquidStakingTypes.CallMethodResult<"topUpInflationPool">> => {
      return callMethod(
        LiquidStaking,
        this,
        "topUpInflationPool",
        params,
        getContractByCodeHash
      );
    },
    setGainPerMillisecond: async (
      params: LiquidStakingTypes.CallMethodParams<"setGainPerMillisecond">
    ): Promise<
      LiquidStakingTypes.CallMethodResult<"setGainPerMillisecond">
    > => {
      return callMethod(
        LiquidStaking,
        this,
        "setGainPerMillisecond",
        params,
        getContractByCodeHash
      );
    },
    setInflationRate: async (
      params: LiquidStakingTypes.CallMethodParams<"setInflationRate">
    ): Promise<LiquidStakingTypes.CallMethodResult<"setInflationRate">> => {
      return callMethod(
        LiquidStaking,
        this,
        "setInflationRate",
        params,
        getContractByCodeHash
      );
    },
    getTokenId: async (
      params?: LiquidStakingTypes.CallMethodParams<"getTokenId">
    ): Promise<LiquidStakingTypes.CallMethodResult<"getTokenId">> => {
      return callMethod(
        LiquidStaking,
        this,
        "getTokenId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    upgrade: async (
      params: LiquidStakingTypes.CallMethodParams<"upgrade">
    ): Promise<LiquidStakingTypes.CallMethodResult<"upgrade">> => {
      return callMethod(
        LiquidStaking,
        this,
        "upgrade",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getSymbol: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"getSymbol">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"getSymbol">> => {
      return signExecuteMethod(LiquidStaking, this, "getSymbol", params);
    },
    getName: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"getName">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(LiquidStaking, this, "getName", params);
    },
    getDecimals: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"getDecimals">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"getDecimals">> => {
      return signExecuteMethod(LiquidStaking, this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<
      LiquidStakingTypes.SignExecuteMethodResult<"getTotalSupply">
    > => {
      return signExecuteMethod(LiquidStaking, this, "getTotalSupply", params);
    },
    pause: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"pause">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"pause">> => {
      return signExecuteMethod(LiquidStaking, this, "pause", params);
    },
    unpause: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"unpause">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"unpause">> => {
      return signExecuteMethod(LiquidStaking, this, "unpause", params);
    },
    whenNotPaused: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"whenNotPaused">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"whenNotPaused">> => {
      return signExecuteMethod(LiquidStaking, this, "whenNotPaused", params);
    },
    onlyOwner: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"onlyOwner">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"onlyOwner">> => {
      return signExecuteMethod(LiquidStaking, this, "onlyOwner", params);
    },
    changeOwner: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"changeOwner">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"changeOwner">> => {
      return signExecuteMethod(LiquidStaking, this, "changeOwner", params);
    },
    getCurrentRewardPerXToken: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"getCurrentRewardPerXToken">
    ): Promise<
      LiquidStakingTypes.SignExecuteMethodResult<"getCurrentRewardPerXToken">
    > => {
      return signExecuteMethod(
        LiquidStaking,
        this,
        "getCurrentRewardPerXToken",
        params
      );
    },
    getCurrentInflationPerXToken: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"getCurrentInflationPerXToken">
    ): Promise<
      LiquidStakingTypes.SignExecuteMethodResult<"getCurrentInflationPerXToken">
    > => {
      return signExecuteMethod(
        LiquidStaking,
        this,
        "getCurrentInflationPerXToken",
        params
      );
    },
    getCurrentPrice: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"getCurrentPrice">
    ): Promise<
      LiquidStakingTypes.SignExecuteMethodResult<"getCurrentPrice">
    > => {
      return signExecuteMethod(LiquidStaking, this, "getCurrentPrice", params);
    },
    updatePrice: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"updatePrice">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"updatePrice">> => {
      return signExecuteMethod(LiquidStaking, this, "updatePrice", params);
    },
    mint: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"mint">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"mint">> => {
      return signExecuteMethod(LiquidStaking, this, "mint", params);
    },
    burn: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"burn">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"burn">> => {
      return signExecuteMethod(LiquidStaking, this, "burn", params);
    },
    topUpRewards: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"topUpRewards">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"topUpRewards">> => {
      return signExecuteMethod(LiquidStaking, this, "topUpRewards", params);
    },
    topUpInflationPool: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"topUpInflationPool">
    ): Promise<
      LiquidStakingTypes.SignExecuteMethodResult<"topUpInflationPool">
    > => {
      return signExecuteMethod(
        LiquidStaking,
        this,
        "topUpInflationPool",
        params
      );
    },
    setGainPerMillisecond: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"setGainPerMillisecond">
    ): Promise<
      LiquidStakingTypes.SignExecuteMethodResult<"setGainPerMillisecond">
    > => {
      return signExecuteMethod(
        LiquidStaking,
        this,
        "setGainPerMillisecond",
        params
      );
    },
    setInflationRate: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"setInflationRate">
    ): Promise<
      LiquidStakingTypes.SignExecuteMethodResult<"setInflationRate">
    > => {
      return signExecuteMethod(LiquidStaking, this, "setInflationRate", params);
    },
    getTokenId: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"getTokenId">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"getTokenId">> => {
      return signExecuteMethod(LiquidStaking, this, "getTokenId", params);
    },
    upgrade: async (
      params: LiquidStakingTypes.SignExecuteMethodParams<"upgrade">
    ): Promise<LiquidStakingTypes.SignExecuteMethodResult<"upgrade">> => {
      return signExecuteMethod(LiquidStaking, this, "upgrade", params);
    },
  };

  async multicall<Calls extends LiquidStakingTypes.MultiCallParams>(
    calls: Calls
  ): Promise<LiquidStakingTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends LiquidStakingTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<LiquidStakingTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | LiquidStakingTypes.MultiCallParams
      | LiquidStakingTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      LiquidStaking,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
