/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as StakingContractJson } from "./Staking.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts-registry";

// Custom types for the contract
export namespace StakingTypes {
  export type Fields = {
    tokenId: HexString;
    rewardsTokenId: HexString;
    stakingAccountTemplateId: HexString;
    rewardRate: bigint;
    totalAmountStaked: bigint;
    rewardPerTokenStored: bigint;
    lastUpdateTime: bigint;
    owner_: Address;
    paused_: boolean;
  };

  export type State = ContractState<Fields>;

  export interface CallMethodTable {
    stakingAccountExists: {
      params: CallContractParams<{ staker: Address }>;
      result: CallContractResult<boolean>;
    };
    getStakingAccount: {
      params: CallContractParams<{ staker: Address }>;
      result: CallContractResult<HexString>;
    };
    createStakingAccount: {
      params: CallContractParams<{
        staker: Address;
        amount: bigint;
        rewardPerTokenPaid: bigint;
      }>;
      result: CallContractResult<null>;
    };
    pause: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    unpause: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    whenNotPaused: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    onlyOwner: {
      params: CallContractParams<{ caller: Address }>;
      result: CallContractResult<null>;
    };
    changeOwner: {
      params: CallContractParams<{ newOwner: Address }>;
      result: CallContractResult<null>;
    };
    getTokenId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getRewardsTokenId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    updateStakerReward: {
      params: CallContractParams<{ account: HexString }>;
      result: CallContractResult<null>;
    };
    updateReward: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    earned: {
      params: CallContractParams<{ acc: HexString }>;
      result: CallContractResult<bigint>;
    };
    calculateRewardPerToken: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    stake: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    unstake: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    sendRewards: {
      params: CallContractParams<{ account: HexString }>;
      result: CallContractResult<null>;
    };
    claimRewards: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    setRewardRate: {
      params: CallContractParams<{ rate: bigint }>;
      result: CallContractResult<null>;
    };
    upgrade: {
      params: CallContractParams<{ newBytecode: HexString }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    stakingAccountExists: {
      params: SignExecuteContractMethodParams<{ staker: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getStakingAccount: {
      params: SignExecuteContractMethodParams<{ staker: Address }>;
      result: SignExecuteScriptTxResult;
    };
    createStakingAccount: {
      params: SignExecuteContractMethodParams<{
        staker: Address;
        amount: bigint;
        rewardPerTokenPaid: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    pause: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    unpause: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    whenNotPaused: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    onlyOwner: {
      params: SignExecuteContractMethodParams<{ caller: Address }>;
      result: SignExecuteScriptTxResult;
    };
    changeOwner: {
      params: SignExecuteContractMethodParams<{ newOwner: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getTokenId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getRewardsTokenId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    updateStakerReward: {
      params: SignExecuteContractMethodParams<{ account: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    updateReward: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    earned: {
      params: SignExecuteContractMethodParams<{ acc: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    calculateRewardPerToken: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    stake: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    unstake: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    sendRewards: {
      params: SignExecuteContractMethodParams<{ account: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    claimRewards: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    setRewardRate: {
      params: SignExecuteContractMethodParams<{ rate: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    upgrade: {
      params: SignExecuteContractMethodParams<{ newBytecode: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<StakingInstance, StakingTypes.Fields> {
  encodeFields(fields: StakingTypes.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  consts = {
    PermissionsErrorCodes: { Forbidden: BigInt("0") },
    ErrorCodes: {
      ReserveOverflow: BigInt("0"),
      InsufficientInitLiquidity: BigInt("1"),
      InsufficientLiquidityMinted: BigInt("2"),
      InsufficientLiquidityBurned: BigInt("3"),
      InvalidToAddress: BigInt("4"),
      InsufficientLiquidity: BigInt("5"),
      InvalidTokenInId: BigInt("6"),
      InvalidCalleeId: BigInt("7"),
      InvalidK: BigInt("8"),
      InsufficientOutputAmount: BigInt("9"),
      InsufficientInputAmount: BigInt("10"),
      IdenticalTokenIds: BigInt("11"),
      Expired: BigInt("12"),
      InsufficientToken0Amount: BigInt("13"),
      InsufficientToken1Amount: BigInt("14"),
      TokenNotExist: BigInt("15"),
      InvalidCaller: BigInt("16"),
      FeeCollectorNotEnabled: BigInt("17"),
    },
    PauseableErrorCodes: { Paused: BigInt("0") },
    StakingAccountErrorCodes: { AlreadyExists: BigInt("0") },
  };

  at(address: string): StakingInstance {
    return new StakingInstance(address);
  }

  tests = {
    stakingAccountExists: async (
      params: TestContractParamsWithoutMaps<
        StakingTypes.Fields,
        { staker: Address }
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(
        this,
        "stakingAccountExists",
        params,
        getContractByCodeHash
      );
    },
    getStakingAccount: async (
      params: TestContractParamsWithoutMaps<
        StakingTypes.Fields,
        { staker: Address }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getStakingAccount",
        params,
        getContractByCodeHash
      );
    },
    createStakingAccount: async (
      params: TestContractParamsWithoutMaps<
        StakingTypes.Fields,
        { staker: Address; amount: bigint; rewardPerTokenPaid: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "createStakingAccount",
        params,
        getContractByCodeHash
      );
    },
    pause: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "pause", params, getContractByCodeHash);
    },
    unpause: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "unpause", params, getContractByCodeHash);
    },
    whenNotPaused: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "whenNotPaused", params, getContractByCodeHash);
    },
    onlyOwner: async (
      params: TestContractParamsWithoutMaps<
        StakingTypes.Fields,
        { caller: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "onlyOwner", params, getContractByCodeHash);
    },
    changeOwner: async (
      params: TestContractParamsWithoutMaps<
        StakingTypes.Fields,
        { newOwner: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "changeOwner", params, getContractByCodeHash);
    },
    getTokenId: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getTokenId", params, getContractByCodeHash);
    },
    getRewardsTokenId: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getRewardsTokenId",
        params,
        getContractByCodeHash
      );
    },
    updateStakerReward: async (
      params: TestContractParamsWithoutMaps<
        StakingTypes.Fields,
        { account: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "updateStakerReward",
        params,
        getContractByCodeHash
      );
    },
    updateReward: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "updateReward", params, getContractByCodeHash);
    },
    earned: async (
      params: TestContractParamsWithoutMaps<
        StakingTypes.Fields,
        { acc: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "earned", params, getContractByCodeHash);
    },
    calculateRewardPerToken: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "calculateRewardPerToken",
        params,
        getContractByCodeHash
      );
    },
    stake: async (
      params: TestContractParamsWithoutMaps<
        StakingTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "stake", params, getContractByCodeHash);
    },
    unstake: async (
      params: TestContractParamsWithoutMaps<
        StakingTypes.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "unstake", params, getContractByCodeHash);
    },
    sendRewards: async (
      params: TestContractParamsWithoutMaps<
        StakingTypes.Fields,
        { account: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "sendRewards", params, getContractByCodeHash);
    },
    claimRewards: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingTypes.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "claimRewards", params, getContractByCodeHash);
    },
    setRewardRate: async (
      params: TestContractParamsWithoutMaps<
        StakingTypes.Fields,
        { rate: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setRewardRate", params, getContractByCodeHash);
    },
    upgrade: async (
      params: TestContractParamsWithoutMaps<
        StakingTypes.Fields,
        { newBytecode: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "upgrade", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: StakingTypes.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const Staking = new Factory(
  Contract.fromJson(
    StakingContractJson,
    "",
    "a0f2928c10d01ba9f2898c17a2f55a0196eaa7e96c492c1b8ff0ac479b80e8de",
    []
  )
);
registerContract(Staking);

// Use this class to interact with the blockchain
export class StakingInstance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<StakingTypes.State> {
    return fetchContractState(Staking, this);
  }

  view = {
    stakingAccountExists: async (
      params: StakingTypes.CallMethodParams<"stakingAccountExists">
    ): Promise<StakingTypes.CallMethodResult<"stakingAccountExists">> => {
      return callMethod(
        Staking,
        this,
        "stakingAccountExists",
        params,
        getContractByCodeHash
      );
    },
    getStakingAccount: async (
      params: StakingTypes.CallMethodParams<"getStakingAccount">
    ): Promise<StakingTypes.CallMethodResult<"getStakingAccount">> => {
      return callMethod(
        Staking,
        this,
        "getStakingAccount",
        params,
        getContractByCodeHash
      );
    },
    createStakingAccount: async (
      params: StakingTypes.CallMethodParams<"createStakingAccount">
    ): Promise<StakingTypes.CallMethodResult<"createStakingAccount">> => {
      return callMethod(
        Staking,
        this,
        "createStakingAccount",
        params,
        getContractByCodeHash
      );
    },
    pause: async (
      params?: StakingTypes.CallMethodParams<"pause">
    ): Promise<StakingTypes.CallMethodResult<"pause">> => {
      return callMethod(
        Staking,
        this,
        "pause",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    unpause: async (
      params?: StakingTypes.CallMethodParams<"unpause">
    ): Promise<StakingTypes.CallMethodResult<"unpause">> => {
      return callMethod(
        Staking,
        this,
        "unpause",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    whenNotPaused: async (
      params?: StakingTypes.CallMethodParams<"whenNotPaused">
    ): Promise<StakingTypes.CallMethodResult<"whenNotPaused">> => {
      return callMethod(
        Staking,
        this,
        "whenNotPaused",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    onlyOwner: async (
      params: StakingTypes.CallMethodParams<"onlyOwner">
    ): Promise<StakingTypes.CallMethodResult<"onlyOwner">> => {
      return callMethod(
        Staking,
        this,
        "onlyOwner",
        params,
        getContractByCodeHash
      );
    },
    changeOwner: async (
      params: StakingTypes.CallMethodParams<"changeOwner">
    ): Promise<StakingTypes.CallMethodResult<"changeOwner">> => {
      return callMethod(
        Staking,
        this,
        "changeOwner",
        params,
        getContractByCodeHash
      );
    },
    getTokenId: async (
      params?: StakingTypes.CallMethodParams<"getTokenId">
    ): Promise<StakingTypes.CallMethodResult<"getTokenId">> => {
      return callMethod(
        Staking,
        this,
        "getTokenId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getRewardsTokenId: async (
      params?: StakingTypes.CallMethodParams<"getRewardsTokenId">
    ): Promise<StakingTypes.CallMethodResult<"getRewardsTokenId">> => {
      return callMethod(
        Staking,
        this,
        "getRewardsTokenId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    updateStakerReward: async (
      params: StakingTypes.CallMethodParams<"updateStakerReward">
    ): Promise<StakingTypes.CallMethodResult<"updateStakerReward">> => {
      return callMethod(
        Staking,
        this,
        "updateStakerReward",
        params,
        getContractByCodeHash
      );
    },
    updateReward: async (
      params?: StakingTypes.CallMethodParams<"updateReward">
    ): Promise<StakingTypes.CallMethodResult<"updateReward">> => {
      return callMethod(
        Staking,
        this,
        "updateReward",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    earned: async (
      params: StakingTypes.CallMethodParams<"earned">
    ): Promise<StakingTypes.CallMethodResult<"earned">> => {
      return callMethod(Staking, this, "earned", params, getContractByCodeHash);
    },
    calculateRewardPerToken: async (
      params?: StakingTypes.CallMethodParams<"calculateRewardPerToken">
    ): Promise<StakingTypes.CallMethodResult<"calculateRewardPerToken">> => {
      return callMethod(
        Staking,
        this,
        "calculateRewardPerToken",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    stake: async (
      params: StakingTypes.CallMethodParams<"stake">
    ): Promise<StakingTypes.CallMethodResult<"stake">> => {
      return callMethod(Staking, this, "stake", params, getContractByCodeHash);
    },
    unstake: async (
      params: StakingTypes.CallMethodParams<"unstake">
    ): Promise<StakingTypes.CallMethodResult<"unstake">> => {
      return callMethod(
        Staking,
        this,
        "unstake",
        params,
        getContractByCodeHash
      );
    },
    sendRewards: async (
      params: StakingTypes.CallMethodParams<"sendRewards">
    ): Promise<StakingTypes.CallMethodResult<"sendRewards">> => {
      return callMethod(
        Staking,
        this,
        "sendRewards",
        params,
        getContractByCodeHash
      );
    },
    claimRewards: async (
      params?: StakingTypes.CallMethodParams<"claimRewards">
    ): Promise<StakingTypes.CallMethodResult<"claimRewards">> => {
      return callMethod(
        Staking,
        this,
        "claimRewards",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    setRewardRate: async (
      params: StakingTypes.CallMethodParams<"setRewardRate">
    ): Promise<StakingTypes.CallMethodResult<"setRewardRate">> => {
      return callMethod(
        Staking,
        this,
        "setRewardRate",
        params,
        getContractByCodeHash
      );
    },
    upgrade: async (
      params: StakingTypes.CallMethodParams<"upgrade">
    ): Promise<StakingTypes.CallMethodResult<"upgrade">> => {
      return callMethod(
        Staking,
        this,
        "upgrade",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    stakingAccountExists: async (
      params: StakingTypes.SignExecuteMethodParams<"stakingAccountExists">
    ): Promise<
      StakingTypes.SignExecuteMethodResult<"stakingAccountExists">
    > => {
      return signExecuteMethod(Staking, this, "stakingAccountExists", params);
    },
    getStakingAccount: async (
      params: StakingTypes.SignExecuteMethodParams<"getStakingAccount">
    ): Promise<StakingTypes.SignExecuteMethodResult<"getStakingAccount">> => {
      return signExecuteMethod(Staking, this, "getStakingAccount", params);
    },
    createStakingAccount: async (
      params: StakingTypes.SignExecuteMethodParams<"createStakingAccount">
    ): Promise<
      StakingTypes.SignExecuteMethodResult<"createStakingAccount">
    > => {
      return signExecuteMethod(Staking, this, "createStakingAccount", params);
    },
    pause: async (
      params: StakingTypes.SignExecuteMethodParams<"pause">
    ): Promise<StakingTypes.SignExecuteMethodResult<"pause">> => {
      return signExecuteMethod(Staking, this, "pause", params);
    },
    unpause: async (
      params: StakingTypes.SignExecuteMethodParams<"unpause">
    ): Promise<StakingTypes.SignExecuteMethodResult<"unpause">> => {
      return signExecuteMethod(Staking, this, "unpause", params);
    },
    whenNotPaused: async (
      params: StakingTypes.SignExecuteMethodParams<"whenNotPaused">
    ): Promise<StakingTypes.SignExecuteMethodResult<"whenNotPaused">> => {
      return signExecuteMethod(Staking, this, "whenNotPaused", params);
    },
    onlyOwner: async (
      params: StakingTypes.SignExecuteMethodParams<"onlyOwner">
    ): Promise<StakingTypes.SignExecuteMethodResult<"onlyOwner">> => {
      return signExecuteMethod(Staking, this, "onlyOwner", params);
    },
    changeOwner: async (
      params: StakingTypes.SignExecuteMethodParams<"changeOwner">
    ): Promise<StakingTypes.SignExecuteMethodResult<"changeOwner">> => {
      return signExecuteMethod(Staking, this, "changeOwner", params);
    },
    getTokenId: async (
      params: StakingTypes.SignExecuteMethodParams<"getTokenId">
    ): Promise<StakingTypes.SignExecuteMethodResult<"getTokenId">> => {
      return signExecuteMethod(Staking, this, "getTokenId", params);
    },
    getRewardsTokenId: async (
      params: StakingTypes.SignExecuteMethodParams<"getRewardsTokenId">
    ): Promise<StakingTypes.SignExecuteMethodResult<"getRewardsTokenId">> => {
      return signExecuteMethod(Staking, this, "getRewardsTokenId", params);
    },
    updateStakerReward: async (
      params: StakingTypes.SignExecuteMethodParams<"updateStakerReward">
    ): Promise<StakingTypes.SignExecuteMethodResult<"updateStakerReward">> => {
      return signExecuteMethod(Staking, this, "updateStakerReward", params);
    },
    updateReward: async (
      params: StakingTypes.SignExecuteMethodParams<"updateReward">
    ): Promise<StakingTypes.SignExecuteMethodResult<"updateReward">> => {
      return signExecuteMethod(Staking, this, "updateReward", params);
    },
    earned: async (
      params: StakingTypes.SignExecuteMethodParams<"earned">
    ): Promise<StakingTypes.SignExecuteMethodResult<"earned">> => {
      return signExecuteMethod(Staking, this, "earned", params);
    },
    calculateRewardPerToken: async (
      params: StakingTypes.SignExecuteMethodParams<"calculateRewardPerToken">
    ): Promise<
      StakingTypes.SignExecuteMethodResult<"calculateRewardPerToken">
    > => {
      return signExecuteMethod(
        Staking,
        this,
        "calculateRewardPerToken",
        params
      );
    },
    stake: async (
      params: StakingTypes.SignExecuteMethodParams<"stake">
    ): Promise<StakingTypes.SignExecuteMethodResult<"stake">> => {
      return signExecuteMethod(Staking, this, "stake", params);
    },
    unstake: async (
      params: StakingTypes.SignExecuteMethodParams<"unstake">
    ): Promise<StakingTypes.SignExecuteMethodResult<"unstake">> => {
      return signExecuteMethod(Staking, this, "unstake", params);
    },
    sendRewards: async (
      params: StakingTypes.SignExecuteMethodParams<"sendRewards">
    ): Promise<StakingTypes.SignExecuteMethodResult<"sendRewards">> => {
      return signExecuteMethod(Staking, this, "sendRewards", params);
    },
    claimRewards: async (
      params: StakingTypes.SignExecuteMethodParams<"claimRewards">
    ): Promise<StakingTypes.SignExecuteMethodResult<"claimRewards">> => {
      return signExecuteMethod(Staking, this, "claimRewards", params);
    },
    setRewardRate: async (
      params: StakingTypes.SignExecuteMethodParams<"setRewardRate">
    ): Promise<StakingTypes.SignExecuteMethodResult<"setRewardRate">> => {
      return signExecuteMethod(Staking, this, "setRewardRate", params);
    },
    upgrade: async (
      params: StakingTypes.SignExecuteMethodParams<"upgrade">
    ): Promise<StakingTypes.SignExecuteMethodResult<"upgrade">> => {
      return signExecuteMethod(Staking, this, "upgrade", params);
    },
  };

  async multicall<Calls extends StakingTypes.MultiCallParams>(
    calls: Calls
  ): Promise<StakingTypes.MultiCallResults<Calls>>;
  async multicall<Callss extends StakingTypes.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<StakingTypes.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends StakingTypes.MultiCallParams | StakingTypes.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(Staking, this, callss, getContractByCodeHash);
  }
}
