/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as StakingV4ContractJson } from "./StakingV4.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts-registry";

// Custom types for the contract
export namespace StakingV4Types {
  export type Fields = {
    tokenId: HexString;
    rewardsTokenId: HexString;
    stakingAccountTemplateId: HexString;
    rewardRate: bigint;
    totalAmountStaked: bigint;
    rewardPerTokenStored: bigint;
    lastUpdateTime: bigint;
    owner_: Address;
    paused_: boolean;
  };

  export type State = ContractState<Fields>;

  export type StakeEvent = ContractEvent<{ staker: Address }>;

  export interface CallMethodTable {
    stakingAccountExists: {
      params: CallContractParams<{ staker: Address }>;
      result: CallContractResult<boolean>;
    };
    getStakingAccount: {
      params: CallContractParams<{ staker: Address }>;
      result: CallContractResult<HexString>;
    };
    createStakingAccount: {
      params: CallContractParams<{
        staker: Address;
        amount: bigint;
        rewardPerTokenPaid: bigint;
      }>;
      result: CallContractResult<null>;
    };
    pause: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    unpause: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    whenNotPaused: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    onlyOwner: {
      params: CallContractParams<{ caller: Address }>;
      result: CallContractResult<null>;
    };
    changeOwner: {
      params: CallContractParams<{ newOwner: Address }>;
      result: CallContractResult<null>;
    };
    getTokenId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getRewardsTokenId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    updateStakerReward: {
      params: CallContractParams<{ account: HexString }>;
      result: CallContractResult<null>;
    };
    updateReward: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    earned: {
      params: CallContractParams<{ acc: HexString }>;
      result: CallContractResult<bigint>;
    };
    calculateRewardPerToken: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    stake: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    unstake: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    sendRewards: {
      params: CallContractParams<{ account: HexString }>;
      result: CallContractResult<null>;
    };
    claimRewards: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    setRewardRate: {
      params: CallContractParams<{ rate: bigint }>;
      result: CallContractResult<null>;
    };
    topUpRewards: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    upgrade: {
      params: CallContractParams<{ newBytecode: HexString }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    stakingAccountExists: {
      params: SignExecuteContractMethodParams<{ staker: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getStakingAccount: {
      params: SignExecuteContractMethodParams<{ staker: Address }>;
      result: SignExecuteScriptTxResult;
    };
    createStakingAccount: {
      params: SignExecuteContractMethodParams<{
        staker: Address;
        amount: bigint;
        rewardPerTokenPaid: bigint;
      }>;
      result: SignExecuteScriptTxResult;
    };
    pause: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    unpause: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    whenNotPaused: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    onlyOwner: {
      params: SignExecuteContractMethodParams<{ caller: Address }>;
      result: SignExecuteScriptTxResult;
    };
    changeOwner: {
      params: SignExecuteContractMethodParams<{ newOwner: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getTokenId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getRewardsTokenId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    updateStakerReward: {
      params: SignExecuteContractMethodParams<{ account: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    updateReward: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    earned: {
      params: SignExecuteContractMethodParams<{ acc: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    calculateRewardPerToken: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    stake: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    unstake: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    sendRewards: {
      params: SignExecuteContractMethodParams<{ account: HexString }>;
      result: SignExecuteScriptTxResult;
    };
    claimRewards: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    setRewardRate: {
      params: SignExecuteContractMethodParams<{ rate: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    topUpRewards: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    upgrade: {
      params: SignExecuteContractMethodParams<{ newBytecode: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<
  StakingV4Instance,
  StakingV4Types.Fields
> {
  encodeFields(fields: StakingV4Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Stake: 0 };
  consts = {
    ErrorCodes: {
      ReserveOverflow: BigInt("0"),
      InsufficientInitLiquidity: BigInt("1"),
      InsufficientLiquidityMinted: BigInt("2"),
      InsufficientLiquidityBurned: BigInt("3"),
      InvalidToAddress: BigInt("4"),
      InsufficientLiquidity: BigInt("5"),
      InvalidTokenInId: BigInt("6"),
      InvalidCalleeId: BigInt("7"),
      InvalidK: BigInt("8"),
      InsufficientOutputAmount: BigInt("9"),
      InsufficientInputAmount: BigInt("10"),
      IdenticalTokenIds: BigInt("11"),
      Expired: BigInt("12"),
      InsufficientToken0Amount: BigInt("13"),
      InsufficientToken1Amount: BigInt("14"),
      TokenNotExist: BigInt("15"),
      InvalidCaller: BigInt("16"),
      FeeCollectorNotEnabled: BigInt("17"),
    },
    StakingAccountErrorCodes: { AlreadyExists: BigInt("0") },
    PauseableErrorCodes: { Paused: BigInt("0") },
    PermissionsErrorCodes: { Forbidden: BigInt("0") },
  };

  at(address: string): StakingV4Instance {
    return new StakingV4Instance(address);
  }

  tests = {
    stakingAccountExists: async (
      params: TestContractParamsWithoutMaps<
        StakingV4Types.Fields,
        { staker: Address }
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(
        this,
        "stakingAccountExists",
        params,
        getContractByCodeHash
      );
    },
    getStakingAccount: async (
      params: TestContractParamsWithoutMaps<
        StakingV4Types.Fields,
        { staker: Address }
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getStakingAccount",
        params,
        getContractByCodeHash
      );
    },
    createStakingAccount: async (
      params: TestContractParamsWithoutMaps<
        StakingV4Types.Fields,
        { staker: Address; amount: bigint; rewardPerTokenPaid: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "createStakingAccount",
        params,
        getContractByCodeHash
      );
    },
    pause: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingV4Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "pause", params, getContractByCodeHash);
    },
    unpause: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingV4Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "unpause", params, getContractByCodeHash);
    },
    whenNotPaused: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingV4Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "whenNotPaused", params, getContractByCodeHash);
    },
    onlyOwner: async (
      params: TestContractParamsWithoutMaps<
        StakingV4Types.Fields,
        { caller: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "onlyOwner", params, getContractByCodeHash);
    },
    changeOwner: async (
      params: TestContractParamsWithoutMaps<
        StakingV4Types.Fields,
        { newOwner: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "changeOwner", params, getContractByCodeHash);
    },
    getTokenId: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingV4Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getTokenId", params, getContractByCodeHash);
    },
    getRewardsTokenId: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingV4Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(
        this,
        "getRewardsTokenId",
        params,
        getContractByCodeHash
      );
    },
    updateStakerReward: async (
      params: TestContractParamsWithoutMaps<
        StakingV4Types.Fields,
        { account: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "updateStakerReward",
        params,
        getContractByCodeHash
      );
    },
    updateReward: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingV4Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "updateReward", params, getContractByCodeHash);
    },
    earned: async (
      params: TestContractParamsWithoutMaps<
        StakingV4Types.Fields,
        { acc: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "earned", params, getContractByCodeHash);
    },
    calculateRewardPerToken: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingV4Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(
        this,
        "calculateRewardPerToken",
        params,
        getContractByCodeHash
      );
    },
    stake: async (
      params: TestContractParamsWithoutMaps<
        StakingV4Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "stake", params, getContractByCodeHash);
    },
    unstake: async (
      params: TestContractParamsWithoutMaps<
        StakingV4Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "unstake", params, getContractByCodeHash);
    },
    sendRewards: async (
      params: TestContractParamsWithoutMaps<
        StakingV4Types.Fields,
        { account: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "sendRewards", params, getContractByCodeHash);
    },
    claimRewards: async (
      params: Omit<
        TestContractParamsWithoutMaps<StakingV4Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "claimRewards", params, getContractByCodeHash);
    },
    setRewardRate: async (
      params: TestContractParamsWithoutMaps<
        StakingV4Types.Fields,
        { rate: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setRewardRate", params, getContractByCodeHash);
    },
    topUpRewards: async (
      params: TestContractParamsWithoutMaps<
        StakingV4Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "topUpRewards", params, getContractByCodeHash);
    },
    upgrade: async (
      params: TestContractParamsWithoutMaps<
        StakingV4Types.Fields,
        { newBytecode: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "upgrade", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: StakingV4Types.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const StakingV4 = new Factory(
  Contract.fromJson(
    StakingV4ContractJson,
    "",
    "0b3f1327a1bfe8c7638c5c543276043e9ad2f19dfe2abd700c8049bc6b39b163",
    []
  )
);
registerContract(StakingV4);

// Use this class to interact with the blockchain
export class StakingV4Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<StakingV4Types.State> {
    return fetchContractState(StakingV4, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeStakeEvent(
    options: EventSubscribeOptions<StakingV4Types.StakeEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      StakingV4.contract,
      this,
      options,
      "Stake",
      fromCount
    );
  }

  view = {
    stakingAccountExists: async (
      params: StakingV4Types.CallMethodParams<"stakingAccountExists">
    ): Promise<StakingV4Types.CallMethodResult<"stakingAccountExists">> => {
      return callMethod(
        StakingV4,
        this,
        "stakingAccountExists",
        params,
        getContractByCodeHash
      );
    },
    getStakingAccount: async (
      params: StakingV4Types.CallMethodParams<"getStakingAccount">
    ): Promise<StakingV4Types.CallMethodResult<"getStakingAccount">> => {
      return callMethod(
        StakingV4,
        this,
        "getStakingAccount",
        params,
        getContractByCodeHash
      );
    },
    createStakingAccount: async (
      params: StakingV4Types.CallMethodParams<"createStakingAccount">
    ): Promise<StakingV4Types.CallMethodResult<"createStakingAccount">> => {
      return callMethod(
        StakingV4,
        this,
        "createStakingAccount",
        params,
        getContractByCodeHash
      );
    },
    pause: async (
      params?: StakingV4Types.CallMethodParams<"pause">
    ): Promise<StakingV4Types.CallMethodResult<"pause">> => {
      return callMethod(
        StakingV4,
        this,
        "pause",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    unpause: async (
      params?: StakingV4Types.CallMethodParams<"unpause">
    ): Promise<StakingV4Types.CallMethodResult<"unpause">> => {
      return callMethod(
        StakingV4,
        this,
        "unpause",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    whenNotPaused: async (
      params?: StakingV4Types.CallMethodParams<"whenNotPaused">
    ): Promise<StakingV4Types.CallMethodResult<"whenNotPaused">> => {
      return callMethod(
        StakingV4,
        this,
        "whenNotPaused",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    onlyOwner: async (
      params: StakingV4Types.CallMethodParams<"onlyOwner">
    ): Promise<StakingV4Types.CallMethodResult<"onlyOwner">> => {
      return callMethod(
        StakingV4,
        this,
        "onlyOwner",
        params,
        getContractByCodeHash
      );
    },
    changeOwner: async (
      params: StakingV4Types.CallMethodParams<"changeOwner">
    ): Promise<StakingV4Types.CallMethodResult<"changeOwner">> => {
      return callMethod(
        StakingV4,
        this,
        "changeOwner",
        params,
        getContractByCodeHash
      );
    },
    getTokenId: async (
      params?: StakingV4Types.CallMethodParams<"getTokenId">
    ): Promise<StakingV4Types.CallMethodResult<"getTokenId">> => {
      return callMethod(
        StakingV4,
        this,
        "getTokenId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getRewardsTokenId: async (
      params?: StakingV4Types.CallMethodParams<"getRewardsTokenId">
    ): Promise<StakingV4Types.CallMethodResult<"getRewardsTokenId">> => {
      return callMethod(
        StakingV4,
        this,
        "getRewardsTokenId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    updateStakerReward: async (
      params: StakingV4Types.CallMethodParams<"updateStakerReward">
    ): Promise<StakingV4Types.CallMethodResult<"updateStakerReward">> => {
      return callMethod(
        StakingV4,
        this,
        "updateStakerReward",
        params,
        getContractByCodeHash
      );
    },
    updateReward: async (
      params?: StakingV4Types.CallMethodParams<"updateReward">
    ): Promise<StakingV4Types.CallMethodResult<"updateReward">> => {
      return callMethod(
        StakingV4,
        this,
        "updateReward",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    earned: async (
      params: StakingV4Types.CallMethodParams<"earned">
    ): Promise<StakingV4Types.CallMethodResult<"earned">> => {
      return callMethod(
        StakingV4,
        this,
        "earned",
        params,
        getContractByCodeHash
      );
    },
    calculateRewardPerToken: async (
      params?: StakingV4Types.CallMethodParams<"calculateRewardPerToken">
    ): Promise<StakingV4Types.CallMethodResult<"calculateRewardPerToken">> => {
      return callMethod(
        StakingV4,
        this,
        "calculateRewardPerToken",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    stake: async (
      params: StakingV4Types.CallMethodParams<"stake">
    ): Promise<StakingV4Types.CallMethodResult<"stake">> => {
      return callMethod(
        StakingV4,
        this,
        "stake",
        params,
        getContractByCodeHash
      );
    },
    unstake: async (
      params: StakingV4Types.CallMethodParams<"unstake">
    ): Promise<StakingV4Types.CallMethodResult<"unstake">> => {
      return callMethod(
        StakingV4,
        this,
        "unstake",
        params,
        getContractByCodeHash
      );
    },
    sendRewards: async (
      params: StakingV4Types.CallMethodParams<"sendRewards">
    ): Promise<StakingV4Types.CallMethodResult<"sendRewards">> => {
      return callMethod(
        StakingV4,
        this,
        "sendRewards",
        params,
        getContractByCodeHash
      );
    },
    claimRewards: async (
      params?: StakingV4Types.CallMethodParams<"claimRewards">
    ): Promise<StakingV4Types.CallMethodResult<"claimRewards">> => {
      return callMethod(
        StakingV4,
        this,
        "claimRewards",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    setRewardRate: async (
      params: StakingV4Types.CallMethodParams<"setRewardRate">
    ): Promise<StakingV4Types.CallMethodResult<"setRewardRate">> => {
      return callMethod(
        StakingV4,
        this,
        "setRewardRate",
        params,
        getContractByCodeHash
      );
    },
    topUpRewards: async (
      params: StakingV4Types.CallMethodParams<"topUpRewards">
    ): Promise<StakingV4Types.CallMethodResult<"topUpRewards">> => {
      return callMethod(
        StakingV4,
        this,
        "topUpRewards",
        params,
        getContractByCodeHash
      );
    },
    upgrade: async (
      params: StakingV4Types.CallMethodParams<"upgrade">
    ): Promise<StakingV4Types.CallMethodResult<"upgrade">> => {
      return callMethod(
        StakingV4,
        this,
        "upgrade",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    stakingAccountExists: async (
      params: StakingV4Types.SignExecuteMethodParams<"stakingAccountExists">
    ): Promise<
      StakingV4Types.SignExecuteMethodResult<"stakingAccountExists">
    > => {
      return signExecuteMethod(StakingV4, this, "stakingAccountExists", params);
    },
    getStakingAccount: async (
      params: StakingV4Types.SignExecuteMethodParams<"getStakingAccount">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"getStakingAccount">> => {
      return signExecuteMethod(StakingV4, this, "getStakingAccount", params);
    },
    createStakingAccount: async (
      params: StakingV4Types.SignExecuteMethodParams<"createStakingAccount">
    ): Promise<
      StakingV4Types.SignExecuteMethodResult<"createStakingAccount">
    > => {
      return signExecuteMethod(StakingV4, this, "createStakingAccount", params);
    },
    pause: async (
      params: StakingV4Types.SignExecuteMethodParams<"pause">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"pause">> => {
      return signExecuteMethod(StakingV4, this, "pause", params);
    },
    unpause: async (
      params: StakingV4Types.SignExecuteMethodParams<"unpause">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"unpause">> => {
      return signExecuteMethod(StakingV4, this, "unpause", params);
    },
    whenNotPaused: async (
      params: StakingV4Types.SignExecuteMethodParams<"whenNotPaused">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"whenNotPaused">> => {
      return signExecuteMethod(StakingV4, this, "whenNotPaused", params);
    },
    onlyOwner: async (
      params: StakingV4Types.SignExecuteMethodParams<"onlyOwner">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"onlyOwner">> => {
      return signExecuteMethod(StakingV4, this, "onlyOwner", params);
    },
    changeOwner: async (
      params: StakingV4Types.SignExecuteMethodParams<"changeOwner">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"changeOwner">> => {
      return signExecuteMethod(StakingV4, this, "changeOwner", params);
    },
    getTokenId: async (
      params: StakingV4Types.SignExecuteMethodParams<"getTokenId">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"getTokenId">> => {
      return signExecuteMethod(StakingV4, this, "getTokenId", params);
    },
    getRewardsTokenId: async (
      params: StakingV4Types.SignExecuteMethodParams<"getRewardsTokenId">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"getRewardsTokenId">> => {
      return signExecuteMethod(StakingV4, this, "getRewardsTokenId", params);
    },
    updateStakerReward: async (
      params: StakingV4Types.SignExecuteMethodParams<"updateStakerReward">
    ): Promise<
      StakingV4Types.SignExecuteMethodResult<"updateStakerReward">
    > => {
      return signExecuteMethod(StakingV4, this, "updateStakerReward", params);
    },
    updateReward: async (
      params: StakingV4Types.SignExecuteMethodParams<"updateReward">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"updateReward">> => {
      return signExecuteMethod(StakingV4, this, "updateReward", params);
    },
    earned: async (
      params: StakingV4Types.SignExecuteMethodParams<"earned">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"earned">> => {
      return signExecuteMethod(StakingV4, this, "earned", params);
    },
    calculateRewardPerToken: async (
      params: StakingV4Types.SignExecuteMethodParams<"calculateRewardPerToken">
    ): Promise<
      StakingV4Types.SignExecuteMethodResult<"calculateRewardPerToken">
    > => {
      return signExecuteMethod(
        StakingV4,
        this,
        "calculateRewardPerToken",
        params
      );
    },
    stake: async (
      params: StakingV4Types.SignExecuteMethodParams<"stake">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"stake">> => {
      return signExecuteMethod(StakingV4, this, "stake", params);
    },
    unstake: async (
      params: StakingV4Types.SignExecuteMethodParams<"unstake">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"unstake">> => {
      return signExecuteMethod(StakingV4, this, "unstake", params);
    },
    sendRewards: async (
      params: StakingV4Types.SignExecuteMethodParams<"sendRewards">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"sendRewards">> => {
      return signExecuteMethod(StakingV4, this, "sendRewards", params);
    },
    claimRewards: async (
      params: StakingV4Types.SignExecuteMethodParams<"claimRewards">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"claimRewards">> => {
      return signExecuteMethod(StakingV4, this, "claimRewards", params);
    },
    setRewardRate: async (
      params: StakingV4Types.SignExecuteMethodParams<"setRewardRate">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"setRewardRate">> => {
      return signExecuteMethod(StakingV4, this, "setRewardRate", params);
    },
    topUpRewards: async (
      params: StakingV4Types.SignExecuteMethodParams<"topUpRewards">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"topUpRewards">> => {
      return signExecuteMethod(StakingV4, this, "topUpRewards", params);
    },
    upgrade: async (
      params: StakingV4Types.SignExecuteMethodParams<"upgrade">
    ): Promise<StakingV4Types.SignExecuteMethodResult<"upgrade">> => {
      return signExecuteMethod(StakingV4, this, "upgrade", params);
    },
  };

  async multicall<Calls extends StakingV4Types.MultiCallParams>(
    calls: Calls
  ): Promise<StakingV4Types.MultiCallResults<Calls>>;
  async multicall<Callss extends StakingV4Types.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<StakingV4Types.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends
      | StakingV4Types.MultiCallParams
      | StakingV4Types.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(
      StakingV4,
      this,
      callss,
      getContractByCodeHash
    );
  }
}
