/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  Address,
  Contract,
  ContractState,
  TestContractResult,
  HexString,
  ContractFactory,
  EventSubscribeOptions,
  EventSubscription,
  CallContractParams,
  CallContractResult,
  TestContractParams,
  ContractEvent,
  subscribeContractEvent,
  subscribeContractEvents,
  testMethod,
  callMethod,
  multicallMethods,
  fetchContractState,
  Asset,
  ContractInstance,
  getContractEventsCurrentCount,
  TestContractParamsWithoutMaps,
  TestContractResultWithoutMaps,
  SignExecuteContractMethodParams,
  SignExecuteScriptTxResult,
  signExecuteMethod,
  addStdIdToFields,
  encodeContractFields,
  Narrow,
} from "@alephium/web3";
import { default as VaultV3ContractJson } from "./VaultV3.ral.json";
import { getContractByCodeHash, registerContract } from "./contracts-registry";

// Custom types for the contract
export namespace VaultV3Types {
  export type Fields = {
    staking: HexString;
    router: HexString;
    owner_: Address;
    feeTo: Address;
    performanceFee: bigint;
    vaultCap: bigint;
    staleBalance: bigint;
    totalSupply: bigint;
  };

  export type State = ContractState<Fields>;

  export type DepositEvent = ContractEvent<{ from: Address; amount: bigint }>;
  export type WithdrawEvent = ContractEvent<{ from: Address; amount: bigint }>;
  export type CompoundedEvent = ContractEvent<{ amount: bigint }>;

  export interface CallMethodTable {
    getSymbol: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getName: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    getDecimals: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    getTotalSupply: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    onlyOwner: {
      params: CallContractParams<{ caller: Address }>;
      result: CallContractResult<null>;
    };
    changeOwner: {
      params: CallContractParams<{ newOwner: Address }>;
      result: CallContractResult<null>;
    };
    getTokenId: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<HexString>;
    };
    earning: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<bigint>;
    };
    setPerformanceFee: {
      params: CallContractParams<{ fee: bigint }>;
      result: CallContractResult<null>;
    };
    getFeeTo: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<Address>;
    };
    setFeeTo: {
      params: CallContractParams<{ to: Address }>;
      result: CallContractResult<null>;
    };
    setVaultCap: {
      params: CallContractParams<{ cap: bigint }>;
      result: CallContractResult<null>;
    };
    withdrawalFee: {
      params: CallContractParams<{ shares: bigint }>;
      result: CallContractResult<bigint>;
    };
    deposit: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    withdraw: {
      params: CallContractParams<{ shares: bigint }>;
      result: CallContractResult<boolean>;
    };
    claimRewards: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    deductPerformanceFee: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    withdrawAllRewards: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    topUp: {
      params: CallContractParams<{ amount: bigint }>;
      result: CallContractResult<null>;
    };
    earn: {
      params: Omit<CallContractParams<{}>, "args">;
      result: CallContractResult<null>;
    };
    upgrade: {
      params: CallContractParams<{ newBytecode: HexString }>;
      result: CallContractResult<null>;
    };
  }
  export type CallMethodParams<T extends keyof CallMethodTable> =
    CallMethodTable[T]["params"];
  export type CallMethodResult<T extends keyof CallMethodTable> =
    CallMethodTable[T]["result"];
  export type MultiCallParams = Partial<{
    [Name in keyof CallMethodTable]: CallMethodTable[Name]["params"];
  }>;
  export type MultiCallResults<T extends MultiCallParams> = {
    [MaybeName in keyof T]: MaybeName extends keyof CallMethodTable
      ? CallMethodTable[MaybeName]["result"]
      : undefined;
  };
  export type MulticallReturnType<Callss extends MultiCallParams[]> = {
    [index in keyof Callss]: MultiCallResults<Callss[index]>;
  };

  export interface SignExecuteMethodTable {
    getSymbol: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getName: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getDecimals: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    getTotalSupply: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    onlyOwner: {
      params: SignExecuteContractMethodParams<{ caller: Address }>;
      result: SignExecuteScriptTxResult;
    };
    changeOwner: {
      params: SignExecuteContractMethodParams<{ newOwner: Address }>;
      result: SignExecuteScriptTxResult;
    };
    getTokenId: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    earning: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    setPerformanceFee: {
      params: SignExecuteContractMethodParams<{ fee: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    getFeeTo: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    setFeeTo: {
      params: SignExecuteContractMethodParams<{ to: Address }>;
      result: SignExecuteScriptTxResult;
    };
    setVaultCap: {
      params: SignExecuteContractMethodParams<{ cap: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdrawalFee: {
      params: SignExecuteContractMethodParams<{ shares: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    deposit: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    withdraw: {
      params: SignExecuteContractMethodParams<{ shares: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    claimRewards: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    deductPerformanceFee: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    withdrawAllRewards: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    topUp: {
      params: SignExecuteContractMethodParams<{ amount: bigint }>;
      result: SignExecuteScriptTxResult;
    };
    earn: {
      params: Omit<SignExecuteContractMethodParams<{}>, "args">;
      result: SignExecuteScriptTxResult;
    };
    upgrade: {
      params: SignExecuteContractMethodParams<{ newBytecode: HexString }>;
      result: SignExecuteScriptTxResult;
    };
  }
  export type SignExecuteMethodParams<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["params"];
  export type SignExecuteMethodResult<T extends keyof SignExecuteMethodTable> =
    SignExecuteMethodTable[T]["result"];
}

class Factory extends ContractFactory<VaultV3Instance, VaultV3Types.Fields> {
  encodeFields(fields: VaultV3Types.Fields) {
    return encodeContractFields(
      addStdIdToFields(this.contract, fields),
      this.contract.fieldsSig,
      []
    );
  }

  eventIndex = { Deposit: 0, Withdraw: 1, Compounded: 2 };
  consts = { PermissionsErrorCodes: { Forbidden: BigInt("0") } };

  at(address: string): VaultV3Instance {
    return new VaultV3Instance(address);
  }

  tests = {
    getSymbol: async (
      params: Omit<
        TestContractParamsWithoutMaps<VaultV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getSymbol", params, getContractByCodeHash);
    },
    getName: async (
      params: Omit<
        TestContractParamsWithoutMaps<VaultV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getName", params, getContractByCodeHash);
    },
    getDecimals: async (
      params: Omit<
        TestContractParamsWithoutMaps<VaultV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getDecimals", params, getContractByCodeHash);
    },
    getTotalSupply: async (
      params: Omit<
        TestContractParamsWithoutMaps<VaultV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "getTotalSupply", params, getContractByCodeHash);
    },
    onlyOwner: async (
      params: TestContractParamsWithoutMaps<
        VaultV3Types.Fields,
        { caller: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "onlyOwner", params, getContractByCodeHash);
    },
    changeOwner: async (
      params: TestContractParamsWithoutMaps<
        VaultV3Types.Fields,
        { newOwner: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "changeOwner", params, getContractByCodeHash);
    },
    getTokenId: async (
      params: Omit<
        TestContractParamsWithoutMaps<VaultV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<HexString>> => {
      return testMethod(this, "getTokenId", params, getContractByCodeHash);
    },
    earning: async (
      params: Omit<
        TestContractParamsWithoutMaps<VaultV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "earning", params, getContractByCodeHash);
    },
    setPerformanceFee: async (
      params: TestContractParamsWithoutMaps<
        VaultV3Types.Fields,
        { fee: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "setPerformanceFee",
        params,
        getContractByCodeHash
      );
    },
    getFeeTo: async (
      params: Omit<
        TestContractParamsWithoutMaps<VaultV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<Address>> => {
      return testMethod(this, "getFeeTo", params, getContractByCodeHash);
    },
    setFeeTo: async (
      params: TestContractParamsWithoutMaps<
        VaultV3Types.Fields,
        { to: Address }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setFeeTo", params, getContractByCodeHash);
    },
    setVaultCap: async (
      params: TestContractParamsWithoutMaps<
        VaultV3Types.Fields,
        { cap: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "setVaultCap", params, getContractByCodeHash);
    },
    withdrawalFee: async (
      params: TestContractParamsWithoutMaps<
        VaultV3Types.Fields,
        { shares: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<bigint>> => {
      return testMethod(this, "withdrawalFee", params, getContractByCodeHash);
    },
    deposit: async (
      params: TestContractParamsWithoutMaps<
        VaultV3Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "deposit", params, getContractByCodeHash);
    },
    withdraw: async (
      params: TestContractParamsWithoutMaps<
        VaultV3Types.Fields,
        { shares: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<boolean>> => {
      return testMethod(this, "withdraw", params, getContractByCodeHash);
    },
    claimRewards: async (
      params: Omit<
        TestContractParamsWithoutMaps<VaultV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "claimRewards", params, getContractByCodeHash);
    },
    deductPerformanceFee: async (
      params: Omit<
        TestContractParamsWithoutMaps<VaultV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "deductPerformanceFee",
        params,
        getContractByCodeHash
      );
    },
    withdrawAllRewards: async (
      params: Omit<
        TestContractParamsWithoutMaps<VaultV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(
        this,
        "withdrawAllRewards",
        params,
        getContractByCodeHash
      );
    },
    topUp: async (
      params: TestContractParamsWithoutMaps<
        VaultV3Types.Fields,
        { amount: bigint }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "topUp", params, getContractByCodeHash);
    },
    earn: async (
      params: Omit<
        TestContractParamsWithoutMaps<VaultV3Types.Fields, never>,
        "testArgs"
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "earn", params, getContractByCodeHash);
    },
    upgrade: async (
      params: TestContractParamsWithoutMaps<
        VaultV3Types.Fields,
        { newBytecode: HexString }
      >
    ): Promise<TestContractResultWithoutMaps<null>> => {
      return testMethod(this, "upgrade", params, getContractByCodeHash);
    },
  };

  stateForTest(
    initFields: VaultV3Types.Fields,
    asset?: Asset,
    address?: string
  ) {
    return this.stateForTest_(initFields, asset, address, undefined);
  }
}

// Use this object to test and deploy the contract
export const VaultV3 = new Factory(
  Contract.fromJson(
    VaultV3ContractJson,
    "",
    "b1f635fc17abc5a6ca157ff2474723e3cf6e1811489b8b79ce10af7f4a326d8d",
    []
  )
);
registerContract(VaultV3);

// Use this class to interact with the blockchain
export class VaultV3Instance extends ContractInstance {
  constructor(address: Address) {
    super(address);
  }

  async fetchState(): Promise<VaultV3Types.State> {
    return fetchContractState(VaultV3, this);
  }

  async getContractEventsCurrentCount(): Promise<number> {
    return getContractEventsCurrentCount(this.address);
  }

  subscribeDepositEvent(
    options: EventSubscribeOptions<VaultV3Types.DepositEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      VaultV3.contract,
      this,
      options,
      "Deposit",
      fromCount
    );
  }

  subscribeWithdrawEvent(
    options: EventSubscribeOptions<VaultV3Types.WithdrawEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      VaultV3.contract,
      this,
      options,
      "Withdraw",
      fromCount
    );
  }

  subscribeCompoundedEvent(
    options: EventSubscribeOptions<VaultV3Types.CompoundedEvent>,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvent(
      VaultV3.contract,
      this,
      options,
      "Compounded",
      fromCount
    );
  }

  subscribeAllEvents(
    options: EventSubscribeOptions<
      | VaultV3Types.DepositEvent
      | VaultV3Types.WithdrawEvent
      | VaultV3Types.CompoundedEvent
    >,
    fromCount?: number
  ): EventSubscription {
    return subscribeContractEvents(VaultV3.contract, this, options, fromCount);
  }

  view = {
    getSymbol: async (
      params?: VaultV3Types.CallMethodParams<"getSymbol">
    ): Promise<VaultV3Types.CallMethodResult<"getSymbol">> => {
      return callMethod(
        VaultV3,
        this,
        "getSymbol",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getName: async (
      params?: VaultV3Types.CallMethodParams<"getName">
    ): Promise<VaultV3Types.CallMethodResult<"getName">> => {
      return callMethod(
        VaultV3,
        this,
        "getName",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getDecimals: async (
      params?: VaultV3Types.CallMethodParams<"getDecimals">
    ): Promise<VaultV3Types.CallMethodResult<"getDecimals">> => {
      return callMethod(
        VaultV3,
        this,
        "getDecimals",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    getTotalSupply: async (
      params?: VaultV3Types.CallMethodParams<"getTotalSupply">
    ): Promise<VaultV3Types.CallMethodResult<"getTotalSupply">> => {
      return callMethod(
        VaultV3,
        this,
        "getTotalSupply",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    onlyOwner: async (
      params: VaultV3Types.CallMethodParams<"onlyOwner">
    ): Promise<VaultV3Types.CallMethodResult<"onlyOwner">> => {
      return callMethod(
        VaultV3,
        this,
        "onlyOwner",
        params,
        getContractByCodeHash
      );
    },
    changeOwner: async (
      params: VaultV3Types.CallMethodParams<"changeOwner">
    ): Promise<VaultV3Types.CallMethodResult<"changeOwner">> => {
      return callMethod(
        VaultV3,
        this,
        "changeOwner",
        params,
        getContractByCodeHash
      );
    },
    getTokenId: async (
      params?: VaultV3Types.CallMethodParams<"getTokenId">
    ): Promise<VaultV3Types.CallMethodResult<"getTokenId">> => {
      return callMethod(
        VaultV3,
        this,
        "getTokenId",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    earning: async (
      params?: VaultV3Types.CallMethodParams<"earning">
    ): Promise<VaultV3Types.CallMethodResult<"earning">> => {
      return callMethod(
        VaultV3,
        this,
        "earning",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    setPerformanceFee: async (
      params: VaultV3Types.CallMethodParams<"setPerformanceFee">
    ): Promise<VaultV3Types.CallMethodResult<"setPerformanceFee">> => {
      return callMethod(
        VaultV3,
        this,
        "setPerformanceFee",
        params,
        getContractByCodeHash
      );
    },
    getFeeTo: async (
      params?: VaultV3Types.CallMethodParams<"getFeeTo">
    ): Promise<VaultV3Types.CallMethodResult<"getFeeTo">> => {
      return callMethod(
        VaultV3,
        this,
        "getFeeTo",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    setFeeTo: async (
      params: VaultV3Types.CallMethodParams<"setFeeTo">
    ): Promise<VaultV3Types.CallMethodResult<"setFeeTo">> => {
      return callMethod(
        VaultV3,
        this,
        "setFeeTo",
        params,
        getContractByCodeHash
      );
    },
    setVaultCap: async (
      params: VaultV3Types.CallMethodParams<"setVaultCap">
    ): Promise<VaultV3Types.CallMethodResult<"setVaultCap">> => {
      return callMethod(
        VaultV3,
        this,
        "setVaultCap",
        params,
        getContractByCodeHash
      );
    },
    withdrawalFee: async (
      params: VaultV3Types.CallMethodParams<"withdrawalFee">
    ): Promise<VaultV3Types.CallMethodResult<"withdrawalFee">> => {
      return callMethod(
        VaultV3,
        this,
        "withdrawalFee",
        params,
        getContractByCodeHash
      );
    },
    deposit: async (
      params: VaultV3Types.CallMethodParams<"deposit">
    ): Promise<VaultV3Types.CallMethodResult<"deposit">> => {
      return callMethod(
        VaultV3,
        this,
        "deposit",
        params,
        getContractByCodeHash
      );
    },
    withdraw: async (
      params: VaultV3Types.CallMethodParams<"withdraw">
    ): Promise<VaultV3Types.CallMethodResult<"withdraw">> => {
      return callMethod(
        VaultV3,
        this,
        "withdraw",
        params,
        getContractByCodeHash
      );
    },
    claimRewards: async (
      params?: VaultV3Types.CallMethodParams<"claimRewards">
    ): Promise<VaultV3Types.CallMethodResult<"claimRewards">> => {
      return callMethod(
        VaultV3,
        this,
        "claimRewards",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    deductPerformanceFee: async (
      params?: VaultV3Types.CallMethodParams<"deductPerformanceFee">
    ): Promise<VaultV3Types.CallMethodResult<"deductPerformanceFee">> => {
      return callMethod(
        VaultV3,
        this,
        "deductPerformanceFee",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    withdrawAllRewards: async (
      params?: VaultV3Types.CallMethodParams<"withdrawAllRewards">
    ): Promise<VaultV3Types.CallMethodResult<"withdrawAllRewards">> => {
      return callMethod(
        VaultV3,
        this,
        "withdrawAllRewards",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    topUp: async (
      params: VaultV3Types.CallMethodParams<"topUp">
    ): Promise<VaultV3Types.CallMethodResult<"topUp">> => {
      return callMethod(VaultV3, this, "topUp", params, getContractByCodeHash);
    },
    earn: async (
      params?: VaultV3Types.CallMethodParams<"earn">
    ): Promise<VaultV3Types.CallMethodResult<"earn">> => {
      return callMethod(
        VaultV3,
        this,
        "earn",
        params === undefined ? {} : params,
        getContractByCodeHash
      );
    },
    upgrade: async (
      params: VaultV3Types.CallMethodParams<"upgrade">
    ): Promise<VaultV3Types.CallMethodResult<"upgrade">> => {
      return callMethod(
        VaultV3,
        this,
        "upgrade",
        params,
        getContractByCodeHash
      );
    },
  };

  transact = {
    getSymbol: async (
      params: VaultV3Types.SignExecuteMethodParams<"getSymbol">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"getSymbol">> => {
      return signExecuteMethod(VaultV3, this, "getSymbol", params);
    },
    getName: async (
      params: VaultV3Types.SignExecuteMethodParams<"getName">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"getName">> => {
      return signExecuteMethod(VaultV3, this, "getName", params);
    },
    getDecimals: async (
      params: VaultV3Types.SignExecuteMethodParams<"getDecimals">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"getDecimals">> => {
      return signExecuteMethod(VaultV3, this, "getDecimals", params);
    },
    getTotalSupply: async (
      params: VaultV3Types.SignExecuteMethodParams<"getTotalSupply">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"getTotalSupply">> => {
      return signExecuteMethod(VaultV3, this, "getTotalSupply", params);
    },
    onlyOwner: async (
      params: VaultV3Types.SignExecuteMethodParams<"onlyOwner">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"onlyOwner">> => {
      return signExecuteMethod(VaultV3, this, "onlyOwner", params);
    },
    changeOwner: async (
      params: VaultV3Types.SignExecuteMethodParams<"changeOwner">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"changeOwner">> => {
      return signExecuteMethod(VaultV3, this, "changeOwner", params);
    },
    getTokenId: async (
      params: VaultV3Types.SignExecuteMethodParams<"getTokenId">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"getTokenId">> => {
      return signExecuteMethod(VaultV3, this, "getTokenId", params);
    },
    earning: async (
      params: VaultV3Types.SignExecuteMethodParams<"earning">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"earning">> => {
      return signExecuteMethod(VaultV3, this, "earning", params);
    },
    setPerformanceFee: async (
      params: VaultV3Types.SignExecuteMethodParams<"setPerformanceFee">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"setPerformanceFee">> => {
      return signExecuteMethod(VaultV3, this, "setPerformanceFee", params);
    },
    getFeeTo: async (
      params: VaultV3Types.SignExecuteMethodParams<"getFeeTo">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"getFeeTo">> => {
      return signExecuteMethod(VaultV3, this, "getFeeTo", params);
    },
    setFeeTo: async (
      params: VaultV3Types.SignExecuteMethodParams<"setFeeTo">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"setFeeTo">> => {
      return signExecuteMethod(VaultV3, this, "setFeeTo", params);
    },
    setVaultCap: async (
      params: VaultV3Types.SignExecuteMethodParams<"setVaultCap">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"setVaultCap">> => {
      return signExecuteMethod(VaultV3, this, "setVaultCap", params);
    },
    withdrawalFee: async (
      params: VaultV3Types.SignExecuteMethodParams<"withdrawalFee">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"withdrawalFee">> => {
      return signExecuteMethod(VaultV3, this, "withdrawalFee", params);
    },
    deposit: async (
      params: VaultV3Types.SignExecuteMethodParams<"deposit">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"deposit">> => {
      return signExecuteMethod(VaultV3, this, "deposit", params);
    },
    withdraw: async (
      params: VaultV3Types.SignExecuteMethodParams<"withdraw">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"withdraw">> => {
      return signExecuteMethod(VaultV3, this, "withdraw", params);
    },
    claimRewards: async (
      params: VaultV3Types.SignExecuteMethodParams<"claimRewards">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"claimRewards">> => {
      return signExecuteMethod(VaultV3, this, "claimRewards", params);
    },
    deductPerformanceFee: async (
      params: VaultV3Types.SignExecuteMethodParams<"deductPerformanceFee">
    ): Promise<
      VaultV3Types.SignExecuteMethodResult<"deductPerformanceFee">
    > => {
      return signExecuteMethod(VaultV3, this, "deductPerformanceFee", params);
    },
    withdrawAllRewards: async (
      params: VaultV3Types.SignExecuteMethodParams<"withdrawAllRewards">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"withdrawAllRewards">> => {
      return signExecuteMethod(VaultV3, this, "withdrawAllRewards", params);
    },
    topUp: async (
      params: VaultV3Types.SignExecuteMethodParams<"topUp">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"topUp">> => {
      return signExecuteMethod(VaultV3, this, "topUp", params);
    },
    earn: async (
      params: VaultV3Types.SignExecuteMethodParams<"earn">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"earn">> => {
      return signExecuteMethod(VaultV3, this, "earn", params);
    },
    upgrade: async (
      params: VaultV3Types.SignExecuteMethodParams<"upgrade">
    ): Promise<VaultV3Types.SignExecuteMethodResult<"upgrade">> => {
      return signExecuteMethod(VaultV3, this, "upgrade", params);
    },
  };

  async multicall<Calls extends VaultV3Types.MultiCallParams>(
    calls: Calls
  ): Promise<VaultV3Types.MultiCallResults<Calls>>;
  async multicall<Callss extends VaultV3Types.MultiCallParams[]>(
    callss: Narrow<Callss>
  ): Promise<VaultV3Types.MulticallReturnType<Callss>>;
  async multicall<
    Callss extends VaultV3Types.MultiCallParams | VaultV3Types.MultiCallParams[]
  >(callss: Callss): Promise<unknown> {
    return await multicallMethods(VaultV3, this, callss, getContractByCodeHash);
  }
}
